# Generated by Django 4.1.7 on 2023-06-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lieu de perte/disparition'),
        ),
        migrations.AddField(
            model_name='objet',
            name='age',
            field=models.IntegerField(blank=True, default=1, verbose_name="L'âge"),
        ),
        migrations.AddField(
            model_name='objet',
            name='description_person',
            field=models.TextField(blank=True, null=True, verbose_name='Autres précisions nécessaires'),
        ),
        migrations.AddField(
            model_name='objet',
            name='is_person',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='objet',
            name='langue',
            field=models.CharField(blank=True, max_length=200, verbose_name='Toutes les langues'),
        ),
        migrations.AddField(
            model_name='objet',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tous les noms'),
        ),
        migrations.AddField(
            model_name='objet',
            name='sexe',
            field=models.CharField(blank=True, max_length=20, verbose_name='Le sexe'),
        ),
        migrations.AddField(
            model_name='objet',
            name='taille',
            field=models.IntegerField(blank=True, default=2, verbose_name='La taille'),
        ),
        migrations.AddField(
            model_name='objet',
            name='teint',
            field=models.CharField(blank=True, max_length=20, verbose_name='Le teint'),
        ),
        migrations.AddField(
            model_name='objet',
            name='worth',
            field=models.IntegerField(blank=True, default=10, verbose_name='La valeur en FCFA'),
        ),
    ]
