# Generated by Django 3.2.13 on 2022-07-03 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Arrondissement',
                'verbose_name_plural': 'Arrondissements',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Departement',
                'verbose_name_plural': 'Departements',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('arrondissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycountry.arrondissement', verbose_name='Arrondissement')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
            },
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycountry.ville', verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'Quartier',
                'verbose_name_plural': 'Quartiers',
            },
        ),
        migrations.AddField(
            model_name='arrondissement',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycountry.departement', verbose_name='Département'),
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrondissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycountry.arrondissement', verbose_name='Arrondissement')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycountry.departement', verbose_name='Département')),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycountry.quartier', verbose_name='Quartier')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycountry.ville', verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
    ]
