# Generated by Django 4.1.7 on 2023-06-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Key',
            new_name='Token',
        ),
    ]
